{-# LANGUAGE ApplicativeDo #-}
{-# LANGUAGE BangPatterns #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE MagicHash #-}
{-# LANGUAGE NumericUnderscores #-}
{-# LANGUAGE OverloadedRecordDot #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE RecursiveDo #-}
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE UnboxedTuples #-}
{-# LANGUAGE ViewPatterns #-}

{-
Load instr can now be replaced by ordinary rs-type mov.

I could use the first 128 words for a symbol table. `mov ip [imm7]`

Yes, words are specified to be big-endian. That way you can write constants into the text without having to byteswap your hex arithmetic.


|          |                      |                                            |
| -------- | -------------------- | ------------------------------------------ |
| r0-r4    | caller save          |                                            |
| r5-r9    | callee save          |                                            |
| ra, rb   | scratch              |                                            |
| rc/ip/pc | caller save          | program counter                            |
| rd/sp    | callee restore       | stack pointer, aka dump                    |
| re/ep    | caller save, if used | environment pointer (closure, `this`, etc) |
| rf/fo    | caller save, if used | frame pointer                              |
|          |                      |                                            |

I don't wanna keep hand-assembling these hextools as the ISA changes.
So instead, I will program it in this new Haskell TTF API and use an evaluator to assemble and link the thing (I suppose this might be a good time to figure out recursive monads? or I could brute-force it by adding another TTF for noting and calcuating with addresses). (This program will still need to pad because) I want to then hand-check the output bytes, really just hand-disassembling and maybe even decompiling them. The output from the Haskell impl can still be a committed artifact "as if" it was hand-written. However, I want to attach "provenence" to each artifact. This one would be "generated by prototype assembler, then disassebled/decompiled and verified by hand". Provenence really end up being the T-diagrams, I suppose.

Well, here's some charts:
```
op mnem fmt
0  add  rs
1  sub  rs
2  mul  rs
3  div  rs
4  and  rs
5  or   rs  (nor?? bc that makes inv easy?)
6  shl  rs
7  shr  rs
8  mov  rs  (aka ld when addr mode is memory)
9  sto  rs
A  jal  rs  (R, pc <- pc, S)
B  
C  cCC  rfx
D  ldi  imm
E  
F  sys  rfx
...

Formats
rs:  ORMS
rfs: ORrfS
imm: ORI

Mode
0-7  : imm
8  9  A  B  C  D  E  F
r  ib li hi ii so eo fo
where:
imm7 = M.S                        small immediate
r    = regs[S]                    register direct
ib   = &mem8[regs[S]]             indirect byte
li   = &mem32[regs[S] & 0xffff]   low register indirect (car)
hi   = &mem32[regs[S] >> 16]      high register indirect (cdr)
ii   = &mem32[regs[S] + r4]       indexed indirect
so   = &mem32[sp - regs[S]]       stack offset
eo   = &mem32[ep + regs[S]]       environment offset
fo   = &mem32[fp + regs[S]]       frame offset


Condition Addressing Mode and Functions `rf`
      ilt | eq | lt | le | gt | ge | ne | 
imm4:  0  | 1  | 2  | 3  | 4  | 5  | 6  | 7
reg:   8  | 9  | A  | B  | C  | D  | E  | F
( so 3-input nor on f switches to subtract and test high bit,
  wheras all others are mask f with [.0 = eq,lt,gt] tests and succeed if non-zero
)

System Functions:
     get | put | | | | | | hlt
imm: 0   | 1   | | | | | | 7
reg: 8   | 9   | | | | | | F

Equivalencies
j +x
j -x
ldb d r4+a    ===    mov r (ib) a  `8dDa`
stb s r4+a    ===    sto s (ib) a  `9sDa`
neg d a       ===    mov d 0; sub d a
inv d a       ===    mov d 0; sub d 1; sub d a
inv d         ===    nor d d
or d s        ===    nor d s; nor d d
```

-}


module Main (main) where

import Prelude hiding (cycle, div, and)
import qualified Prelude

import Control.Applicative((<**>))
import Control.Exception (catch, throw)
import Control.Monad.Fix (MonadFix)
import Control.Monad (forM, forM_, when, void)
import Control.Monad.IO.Class (liftIO)
import Control.Monad.Primitive (RealWorld)
import Control.Monad.State (State, gets, modify, execState)
import Control.Monad.Trans.Reader (ReaderT, runReaderT, ask)
import Data.Bifunctor (first)
import Data.Bits (Bits, shiftR, shiftL, (.&.), (.|.), complement)
import Data.Char (ord, chr)
import Data.Function ((&))
import Data.Primitive.ByteArray (MutableByteArray, newByteArray, readByteArray, writeByteArray)
import Data.Primitive (sizeOfType)
import Data.Void (Void)
import Data.Word (Word8, Word16, Word32)
import Numeric (showHex)
import Options.Applicative (Parser, info, progDesc, hsubparser)
import Options.Applicative (command, argument, metavar)
import System.Environment (getArgs)
import System.Exit (ExitCode(..), exitWith)
import System.IO.Error (isEOFError)
import System.IO (stdin, stdout, withFile, IOMode(ReadMode), hGetChar, hPutChar, hSetEncoding, latin1, Handle)

import qualified Options.Applicative as Opts

main :: IO ()
main = do
  opts <- Opts.execParser $ info (cliOptions <**> Opts.helper)
    (  progDesc "suite of prototype kiss tools"
    )
  print opts

  case opts.cliCommand of
    CmdExample{..} -> do
      asm <- case exampleName of
        "hello" -> pure helloAsm
      case exampleType of
        "hex" -> putStrLn $ hexdump $ runAsm asm

  -- progFile <- parseArgs
  -- st <- withFile progFile ReadMode $ \fp -> do
  --   hSetEncoding fp latin1
  --   loadExeFile fp
  -- -- FIXME someday the i/o streams and block devices will be loaded instead of assumed from global
  -- hSetEncoding stdin latin1
  -- hSetEncoding stdout latin1
  -- runVm st cycle

  -- let i :: Instruction r => r
  --     i = decodeIntruction 0xF07A
  -- putStrLn $ showHex (i @Word16) ""
  -- st <- newVmSt 1234
  -- runVm st $ do
  --   i

------------------------------------
------ Command Line Interface ------
------------------------------------

data CliOptions = CliOptions
  { cliCommand :: !CliCommand
  }
  deriving (Show)
data CliCommand
  = CmdExample
    { exampleName :: !String
    , exampleType :: !String
    }
  deriving (Show)

cliOptions :: Parser CliOptions
cliOptions = do
  cliCommand <- hsubparser
    (  command "example" (info cmdExample (progDesc "generate example kiss files"))
    )
  pure CliOptions{..}

cmdExample :: Parser CliCommand
cmdExample = do
  exampleName <- argument Opts.str (metavar "NAME")
  exampleType <- argument Opts.str (metavar "TYPE")
  pure CmdExample{..}

parseArgs :: IO FilePath
parseArgs = do
  progFile <- getArgs >>= \case
    "-?" : _ -> help >> exitWith ExitSuccess
    "--help" : _ -> help >> exitWith ExitSuccess
    ["--", path] -> pure path
    [path] -> pure path
    -- TODO accept "-" as stdin
    _ -> help >> exitWith (ExitFailure 1)
  pure progFile

help :: IO ()
help = do
  putStrLn "usage: kissvm PROG"
  putStrLn "    loads and executes a kiss vm binary"
  putStrLn ""
  putStrLn "  --help, -?: display this help message and exit"

-----------------------------
------ Kiss Exe Format ------
-----------------------------

data ExeHeader = ExeHdr
  { entryPoint :: Word32
  , codeSize :: Word32
  , stackBase :: Word32
  , maxMem :: Word32
  }

loadExeFile :: Handle -> IO VmSt
loadExeFile fp = do
  () <- findHeader
  hdr <- loadHeader
  initVm hdr
  where

  findHeader = do
    c0 <- hGetChar fp
    c1 <- case c0 of
      '#' -> loop
        where
        loop = hGetChar fp >>= \case
          '\n' -> hGetChar fp
          _ -> loop
      _ -> pure c0
    magic <- fmap (c1:) $ forM [1..7] $ \(_::Int) -> hGetChar fp
    case magic of
      "kiss vm\0" -> pure ()
      _ -> error "missing magic"

  loadHeader = do
    let be32 :: IO Word32
        be32 = do
          bytes <- forM [1..4] $ \(_::Int) -> fromIntegral . ord <$> hGetChar fp
          pure $ foldl (\hi lo -> (hi `shiftL` 8) .|. lo) 0 bytes
    forM_ [1..8] $ \(_::Int) -> hGetChar fp -- 8-byte padding
    entryPoint <- be32
    codeSize <- be32
    stackBase <- be32
    maxMem <- be32
    when (codeSize <= entryPoint) $ error "entry point exceeds program size"
    when (stackBase < codeSize) $ error "stack position starts inside program"
    when (maxMem < stackBase) $ error "stack position exceeds max memory"
    when (0x4_0000 < maxMem) $ error "required memory exceeeds maximum arcitecture memory"
    pure ExeHdr{..}

  initVm :: ExeHeader -> IO VmSt
  initVm hdr = do
    st <- newVmSt hdr.maxMem
    runVm st $ do
      st32be 0 0             -- mem32[0] = 0
      st32be 4 hdr.codeSize  -- mem32[1] = codeSize (ie bottom of heap)
      st32be 8 hdr.stackBase -- mem32[2] = stackBase (ie top of heap)
      st32be 12 hdr.maxMem   -- mem32[3] = maxMem in bytes
      forM_ [16 .. hdr.codeSize-1] $ \i -> do -- load rest of program text
        b <- Vm $ liftIO $ fromIntegral . ord <$> hGetChar fp -- FIXME
        st8 i b
      writeReg 0xD hdr.stackBase -- set sp
      writeReg 0xF hdr.stackBase -- set fp
      writeReg 0xC hdr.entryPoint -- set pc
    pure st

-------------------
------ Codec ------
-------------------

instance Instruction Word16 where
  instr = encodeInstruction

encodeInstruction :: Opcode -> AllOpds -> Word16
encodeInstruction op (OpdR r, s, x, i, c, f) =
  let op16 = (fromIntegral $ encodeOpcode op) `shiftL` 12
      r16  = (fromIntegral $ r) `shiftL` 8
      s16  = (fromIntegral $ encodeOpdS s)
      x16  = (fromIntegral $ encodeOpdX x)
      i16  = (fromIntegral $ i)
      c16  = (fromIntegral $ encodeCond c) `shiftL` 4
      f16  = (fromIntegral $ encodeSysfunc f) `shiftL` 4
   in op16 .|. r16 .|. s16 .|. x16 .|. i16 .|. c16 .|. f16

decodeIntruction :: Instruction r => Word16 -> r
decodeIntruction code =
  let op = decodeOpcode  . fromIntegral $ (code .&. 0xF000) `shiftR` 12
      r  = OpdR          . fromIntegral $ (code .&. 0x0F00) `shiftR` 8
      s  = decodeOpdS    . fromIntegral $  code .&. 0x00FF
      x  = decodeOpdX    . fromIntegral $  code .&. 0x008F
      i  =                 fromIntegral $  code .&. 0x00FF
      c  = decodeCond    . fromIntegral $ (code .&. 0x0070) `shiftR` 4
      f  = decodeSysfunc . fromIntegral $ (code .&. 0x0070) `shiftR` 4
   in op (r, s, x, i, c, f)

------ Instruction Field Helpers ------

encodeOpcode :: Opcode -> Word4
encodeOpcode op = case lookup op (fst <$> codecOpcode @Void) of
  Just it -> it
  Nothing -> error $ "internal: opcode " ++ show op ++ " encoding not defined"
decodeOpcode :: Instruction r => Word4 -> AllOpds -> r
decodeOpcode w4 = case lookup w4 (first snd <$> codecOpcode) of
  Just op -> op
  Nothing -> error $ "unknown opcode " ++ show w4
codecOpcode :: Instruction r => [((Opcode, Word4), AllOpds -> r)]
codecOpcode =
  [ ((Add, 0x0), \(r, s, _, _, _, _) -> add r s)
  , ((Sub, 0x1), \(r, s, _, _, _, _) -> sub r s)
  , ((Mul, 0x2), \(r, s, _, _, _, _) -> mul r s)
  , ((Div, 0x3), \(r, s, _, _, _, _) -> div r s)
  , ((And, 0x4), \(r, s, _, _, _, _) -> and r s)
  , ((Nor, 0x5), \(r, s, _, _, _, _) -> nor r s)
  , ((Shl, 0x6), \(r, s, _, _, _, _) -> shl r s)
  , ((Shr, 0x7), \(r, s, _, _, _, _) -> shr r s)
  , ((Mov, 0x8), \(r, s, _, _, _, _) -> mov r s)
  , ((Sto, 0x9), \(r, s, _, _, _, _) -> sto r s)
  , ((Jal, 0xA), \(r, s, _, _, _, _) -> jal r s)
  , ((Ccc, 0xC), \(r, _, x, _, c, _) -> cCC r c x)
  , ((Ldi, 0xD), \(r, _, _, i, _, _) -> ldi r i)
  , ((Sys, 0xF), \(r, _, x, _, _, f) -> sys r f x)
  ]

encodeOpdS :: OperandS -> Word8
encodeOpdS (OpdSImm imm7) = fromIntegral imm7
encodeOpdS (OpdSReg mode reg) = encodeMode mode .|. fromIntegral reg
decodeOpdS :: Word8 -> OperandS
decodeOpdS w8 =
  let imm7 = fromIntegral $ w8 .&. 0x7F
      mode = decodeMode w8
      reg  = fromIntegral $ w8 .&. 0xF
   in if w8 .&. 0x80 == 0
      then OpdSImm imm7
      else OpdSReg mode reg

encodeMode :: AddrMode -> Word8
encodeMode m = case lookup m codecMode of
  Just w8 -> w8
  Nothing -> error $ "internal: addressing mode " ++ show m ++ "encoding not defined"
decodeMode :: Word8 -> AddrMode
decodeMode w8 = case lookup (w8 .&. 0x70) (swap <$> codecMode) of
  Just m -> m
  Nothing -> error $ "unknown addressing mode " ++ show w8
codecMode :: [(AddrMode, Word8)]
codecMode =
  [ (Direct         , 0x00)
  , (Byte           , 0x10)
  , (Stack          , 0x50)
  , (Env            , 0x60)
  , (Frame          , 0x70)
  ]

encodeOpdX :: OperandX -> Word8
encodeOpdX x = case lookup x codecOpdX of
  Just w8 -> w8
  Nothing -> error $ "internal: x-operand " ++ show x ++ "encoding not defined"
decodeOpdX :: Word8 -> OperandX
decodeOpdX w8 = case lookup (w8 .&. 0x8F) (swap <$> codecOpdX) of
  Just x -> x
  Nothing -> error $ "unknown x-operand: " ++ show w8
codecOpdX :: [(OperandX, Word8)]
codecOpdX =
  [ (OpdXImm $ fromIntegral imm, imm)
  | imm <- [0x00..0x0F]
  ] ++
  [ (OpdXReg $ fromIntegral reg, 0x80 .|. reg)
  | reg <- [0x00..0x0F]
  ]

encodeCond :: Condition -> Word4
encodeCond f = case lookup f codecCond of
  Just w4 -> w4
  Nothing -> error $ "internal: condition " ++ show f ++ "encoding not defined"
decodeCond :: Word4 -> Condition
decodeCond w4 = case lookup w4 (swap <$> codecCond) of
  Just f -> f
  Nothing -> error $ "unknown condition: " ++ show w4
codecCond :: [(Condition, Word4)]
codecCond =
  [ (ILtZ, 0)
  , (UEq , 1)
  , (ULt , 2)
  , (ULe , 3)
  , (UGt , 4)
  , (UGe , 5)
  , (UNe , 6)
  ]

encodeSysfunc :: SysFunc -> Word4
encodeSysfunc f = case lookup f codecSysfunc of
  Just w4 -> w4
  Nothing -> error $ "internal: sysfunc " ++ show f ++ "encoding not defined"
decodeSysfunc :: Word4 -> SysFunc
decodeSysfunc w4 = case lookup w4 (swap <$> codecSysfunc) of
  Just f -> f
  Nothing -> error $ "unknown sysfunc: " ++ show w4
codecSysfunc :: [(SysFunc, Word4)]
codecSysfunc =
  [ (Get, 0)
  , (Put, 1)
  , (Hlt, 7)
  ]

---------------------------------
------ Typed Tagless Final ------
---------------------------------

class Instruction r where
  {-# MINIMAL instr |
   add, sub, mul, div, and, nor, shl, shr, mov, sto, jal, cCC, ldi, sys #-}

  instr :: Opcode -> AllOpds -> r

  add :: OperandR -> OperandS -> r
  sub :: OperandR -> OperandS -> r
  mul :: OperandR -> OperandS -> r
  div :: OperandR -> OperandS -> r
  and :: OperandR -> OperandS -> r
  nor :: OperandR -> OperandS -> r
  shl :: OperandR -> OperandS -> r
  shr :: OperandR -> OperandS -> r
  mov :: OperandR -> OperandS -> r
  sto :: OperandR -> OperandS -> r
  jal :: OperandR -> OperandS -> r
  cCC :: OperandR -> Condition -> OperandX -> r
  ldi :: OperandR -> Word8 -> r
  sys :: OperandR -> SysFunc -> OperandX -> r

  instr Add (r, s, _, _, _, _) = add r s
  instr Sub (r, s, _, _, _, _) = sub r s
  instr Mul (r, s, _, _, _, _) = mul r s
  instr Div (r, s, _, _, _, _) = div r s
  instr And (r, s, _, _, _, _) = and r s
  instr Nor (r, s, _, _, _, _) = nor r s
  instr Shl (r, s, _, _, _, _) = shl r s
  instr Shr (r, s, _, _, _, _) = shr r s
  instr Mov (r, s, _, _, _, _) = mov r s
  instr Sto (r, s, _, _, _, _) = sto r s
  instr Jal (r, s, _, _, _, _) = jal r s
  instr Ccc (r, _, x, _, c, _) = cCC r c x
  instr Ldi (r, _, _, i, _, _) = ldi r i
  instr Sys (r, _, x, _, _, f) = sys r f x
  add r s = instr Add $ fmtRS r s
  sub r s = instr Sub $ fmtRS r s
  mul r s = instr Mul $ fmtRS r s
  div r s = instr Div $ fmtRS r s
  and r s = instr And $ fmtRS r s
  nor r s = instr Nor $ fmtRS r s
  shl r s = instr Shl $ fmtRS r s
  shr r s = instr Shr $ fmtRS r s
  mov r s = instr Mov $ fmtRS r s
  sto r s = instr Sto $ fmtRS r s
  jal r s = instr Jal $ fmtRS r s
  cCC r c x = instr Ccc $ fmtRFX r (Left c) x
  ldi r i = instr Ldi $ fmtRI r i
  sys r f x = instr Sys $ fmtRFX r (Right f) x

data Opcode = Add | Sub | Mul | Div
            | And | Nor | Shl | Shr
            | Mov | Sto | Jal
            | Ccc | Ldi       | Sys
  deriving(Eq, Show)

data OperandR = OpdR Word4
  deriving(Eq, Show)
data OperandS
  = OpdSImm Word7
  | OpdSReg AddrMode Word4
  deriving(Eq, Show)
data OperandX
  = OpdXImm Word4
  | OpdXReg Word4
  deriving(Eq, Show)

data AddrMode
  = Direct
  | Byte
  -- TODO gotta think about this one | PcRel -- [sp - s*4] 0xC for program counter
  | Stack -- [sp - s*4] 0xD for dump
  | Env -- [ep + s*4] 0xE
  | Frame -- [fp + s*4] 0xF
  deriving (Eq, Show)

data Condition
  = ILtZ   -- FIXME not ILt?
  | UEq | UNe
  | ULt | ULe | UGt | UGe
  deriving (Eq, Show)

data SysFunc
  = Get | Put
  | Hlt
  deriving (Eq, Show)

instance Instruction Void where
  instr _ _ = error "attempt to use Instruction Void"

------ Instruction Formats ------

type AllOpds = (OperandR, OperandS, OperandX, Word8, Condition, SysFunc)

fmtRS  :: OperandR                             -> OperandS -> AllOpds
fmtRFX :: OperandR -> Either Condition SysFunc -> OperandX -> AllOpds
fmtRI  :: OperandR                             -> Word8    -> AllOpds

fmtRS  r           s = zeroOpds & \(_, _, x, i, c, f) -> (r, s, x, i, c, f)
fmtRFX r (Left c)  x = zeroOpds & \(_, s, _, i, _, f) -> (r, s, x, i, c, f)
fmtRFX r (Right f) x = zeroOpds & \(_, s, _, i, c, _) -> (r, s, x, i, c, f)
fmtRI  r           i = zeroOpds & \(_, s, x, _, c, f) -> (r, s, x, i, c, f)

zeroOpds :: AllOpds
zeroOpds = (OpdR 0, OpdSImm 0, OpdXImm 0, 0, ILtZ, Get)

------ Architectural Data Types ------

newtype Word4 = W4 { unW4 :: Word8 }
  deriving (Eq, Ord, Real)
instance Show Word4 where
  show = show . unW4
instance Enum Word4 where
  fromEnum = fromEnum . unW4
  toEnum = W4 . (.&. 0xF) . fromIntegral
instance Num Word4 where
  fromInteger = W4 . (.&. 0xF) . fromInteger
  a + b = W4 . (0xF .&.) $ unW4 a + unW4 b
  a * b = W4 . (0xF .&.) $ unW4 a * unW4 b
  abs a = W4 . (0xF .&.) $ abs (unW4 a)
  signum a = W4 . (0xF .&.) $ signum (unW4 a)
  negate a = W4 . (0xF .&.) $ negate (unW4 a)
instance Integral Word4 where
  toInteger = toInteger . unW4
  a `quotRem` b = both (W4 . (.&. 0xF)) $ unW4 a `quotRem` unW4 b

newtype Word7 = W7 { unW7 :: Word8 }
  deriving (Eq, Ord, Real)
instance Show Word7 where
  show = show . unW7
instance Enum Word7 where
  fromEnum = fromEnum . unW7
  toEnum = W7 . (.&. 0x7F) . fromIntegral
instance Num Word7 where
  fromInteger = W7 . (.&. 0x7F) . fromInteger
  a + b = W7 . (0x7F .&.) $ unW7 a + unW7 b
  a * b = W7 . (0x7F .&.) $ unW7 a * unW7 b
  abs a = W7 . (0x7F .&.) $ abs (unW7 a)
  signum a = W7 . (0x7F .&.) $ signum (unW7 a)
  negate a = W7 . (0x7F .&.) $ negate (unW7 a)
instance Integral Word7 where
  toInteger = toInteger . unW7
  a `quotRem` b = both (W7 . (.&. 0x7F)) $ unW7 a `quotRem` unW7 b

-----------------------------
------ Virtual Machine ------
-----------------------------

cycle :: Vm ()
cycle = cycle1 >> cycle

cycle1 :: Vm ()
cycle1 = do
  code <- fetch
  let action = decodeIntruction code
  action

fetch :: Vm Word16
fetch = ld16be =<< incPc

instance Instruction (Vm ()) where
  add dst src = binOpR (+) dst (effR dst) (effS src)
  sub dst src = binOpR (-) dst (effR dst) (effS src)
  mul dst src = binOpR (*) dst (effR dst) (effS src)
  div dst src = binOpR Prelude.div dst (effR dst) (effS src)
  and dst src = binOpR (.&.) dst (effR dst) (effS src)
  nor dst src = binOpR (.~|.) dst (effR dst) (effS src)
  shl dst src = binOpR shiftL dst (effR dst) (fromIntegral <$> effS src)
  shr dst src = binOpR shiftR dst (effR dst) (fromIntegral <$> effS src)
  mov dst src = binOpR const dst (effS src) (pure ())
  sto val addr = lea addr >>= \case
    Left byteAddr  -> st8     byteAddr      =<< (fromIntegral <$> effR val)
    Right wordAddr -> st32be (4 * wordAddr) =<< (fromIntegral <$> effR val)
  jal (OpdR dst) src = do
    target <- effS src
    readReg 0xC >>= writeReg dst
    writeReg 0xC target
  cCC (OpdR a) f b = do
    x <- readReg a
    y <- effX b
    if condition x f y
    then pure ()
    else void $ incPc
  ldi (OpdR dst) imm = writeReg dst (fromIntegral imm)
  sys (OpdR dst) Get _ = do
    writeReg dst =<< vmGet
  sys src Put _ = do
    effR src >>= vmPut
  sys _ Hlt src = do
    code <- fromIntegral . (.&. 0xFF) <$> effX src
    vmHalt code

binOpR :: (a -> b -> Word32)
      -> OperandR
      -> Vm a
      -> Vm b
      -> Vm ()
binOpR f (OpdR dst) a b = writeReg dst =<< (f <$> a <*> b)

------ Decode ------
effR :: OperandR -> Vm Word32
effR (OpdR i) = readReg i

effS :: OperandS -> Vm Word32
effS (OpdSImm w7) = pure $ fromIntegral w7
-- TODO which means that imediate and direct mode in sto would target the addr in the register, where all others target the address that would have been calculated for a load
effS (OpdSReg Direct i) = readReg i
effS src@(OpdSReg _ _) = lea src >>= \case
  Right wordAddr -> ldWord wordAddr
  Left byteAddr -> fromIntegral <$> ld8 byteAddr

effX :: OperandX -> Vm Word32
effX (OpdXImm w4) = pure $ fromIntegral w4
effX (OpdXReg i) = readReg i

-- gets either a byte address or a word address
lea :: OperandS -> Vm (Either Word32 Word32)
lea (OpdSImm w7) = pure . Right $ fromIntegral w7
lea (OpdSReg mode i) = case mode of
  Direct -> Right <$> readReg i
  Byte -> Left <$> do
    base <- readReg i
    pure $ base
  Stack -> Right <$> do
    sp <- readReg 0xD
    off <- readReg i
    pure (sp - off)
  Env -> Right <$> do
    ep <- readReg 0xE
    off <- readReg i
    pure (ep + off)
  Frame -> Right <$> do
    fp <- readReg 0xF
    off <- readReg i
    pure (fp + off)

condition :: Word32 -> Condition -> Word32 -> Bool
condition a f b =
  let flags = (if a == b then 1 else 0) .|.
              (if a < b then 2 else 0) .|.
              (if a > b then 4 else 0) .|.
              (if a > 0x7FFF_FFFF then 8 else 0)
   in flags .&. mask f /= 0
  where
  mask :: Condition -> Int
  mask UEq = 1
  mask ULt = 2
  mask ULe = 3
  mask UGt = 4
  mask UGe = 5
  mask UNe = 6
  mask ILtZ = 8

------ The Machine ------
newtype Vm a = Vm { unVm :: ReaderT VmSt IO a }
  deriving (Functor, Applicative, Monad)
runVm :: VmSt -> Vm a -> IO a
runVm st action = do
  runReaderT (unVm action) st

data VmSt = VmSt
  { mem :: MutableByteArray RealWorld
  , regs :: MutableByteArray RealWorld
  }

newVmSt :: Word32 -> IO VmSt
newVmSt memBytes = VmSt
  <$> newByteArray (fromIntegral memBytes)
  <*> newByteArray (fromIntegral $ 16 * sizeOfType @Word32)


------ register file ------
readReg :: Word4 -> Vm Word32
readReg (fromIntegral -> i) = Vm $ ask >>= \vm -> readByteArray vm.regs i

writeReg :: Word4 -> Word32 -> Vm ()
writeReg (fromIntegral -> i) v = Vm $ ask >>= \vm -> writeByteArray vm.regs i v

incPc :: Vm Word32
incPc = do
  pc <- readReg 0xC
  writeReg 0xC (pc + 2)
  pure pc

------ memory unit ------
ld8 :: Word32 -> Vm Word8
ld8 (fromIntegral -> addr) = Vm $ ask >>= \vm -> readByteArray vm.mem addr

st8 :: Word32 -> Word8 -> Vm ()
st8 (fromIntegral -> addr) v = Vm $ ask >>= \vm -> writeByteArray vm.mem addr v

ld16be :: Word32 -> Vm Word16
ld16be addr = do
  hi <- fromIntegral <$> ld8 addr
  lo <- fromIntegral <$> ld8 (addr + 1)
  pure $ (hi `shiftL` 8) .|. lo

ld32be :: Word32 -> Vm Word32
ld32be addr = do
  bytes <- forM [0..3] $ \i -> fromIntegral <$> ld8 (addr + i)
  pure $ foldr (\hi lo -> (hi `shiftL` 8) .|. lo) 0 bytes

ldWord :: Word32 -> Vm Word32
ldWord addr = ld32be (4*addr)

st32be :: Word32 -> Word32 -> Vm ()
st32be addr w32 = do
  forM_ [0..3] $ \off -> do
    let byteIx = 3 - fromIntegral off
        w8 = fromIntegral $ (w32 `shiftR` byteIx) .&. 0xFF
    st8 (addr + off) w8

------ input/output ------
--FIXME these should be injected dependencies to the Vm monad

vmGet :: Vm Word32
vmGet = Vm $ do
  i <- liftIO $ (ord <$> hGetChar stdin) `catch` onEofError
  pure $ fromIntegral i
  where
  onEofError :: IOError -> IO Int
  onEofError exn = if isEOFError exn then pure (-1) else throw exn

vmPut :: Word32 -> Vm ()
vmPut v = Vm $ liftIO $ hPutChar stdout $ (chr . fromIntegral) v

vmHalt :: Word8 -> Vm ()
vmHalt 0 = Vm $ liftIO $ exitWith ExitSuccess
vmHalt code = Vm $ liftIO $ exitWith $ ExitFailure (fromIntegral code)

-----------------------
------ Assembler ------
-----------------------

helloAsm :: Asm ()
helloAsm = mdo
  asmWord atMain
  asmWord atEnd
  asmWord atEnd
  asmWord atEnd
  atHello <- asmHere
  asmAscii "hello world!\n"
  atHelloEnd <- asmHere
  let helloLen = atHelloEnd - atHello
  asmPad 16
  (atMain, atLoopEnd) <- asmBlock
    [ mov (OpdR 0) (OpdSImm 0)
    , mov (OpdR 3) (OpdSImm $ fromIntegral helloLen)
    , mov (OpdR 4) (OpdSImm $ fromIntegral atHello)
    , cCC (OpdR 4) UEq (OpdXReg 3)
    , sys (OpdR 0) Hlt (OpdXImm 0)
    , mov (OpdR 1) (OpdSReg Byte 0)
    , sys (OpdR 1) Put (OpdXImm 0)
    , add (OpdR 4) (OpdSImm 1)
    , sub (OpdR 0xC) (OpdSImm $ fromIntegral $ atLoopEnd - atMain)
    ]
  asmPad 16
  atEnd <- asmHere
  pure ()

-- TODO turns out StateT is a MonadFix, so we can already get a linker like, eg
-- rec do
--   add (OpdR 0xC) (OpdSImm $ target - from)
--   from <- here
--   ...
--   target <- here
--   ...

instance Instruction (Asm ()) where
  instr op opds = asmInstr (instr op opds)

asmByte :: Word8 -> Asm ()
asmByte b = Asm $ modify $ \st -> st
  { asmCur = st.asmCur + 1
  , asmOut = b : st.asmOut
  }

asmHere :: Asm Word32
asmHere = Asm $ gets asmCur

------ Assembler Utilities ------

asmWord :: Word32 -> Asm ()
asmWord word = forM_ [3,2,1,0] $ \i -> do
  let byte = (word `shiftL` (8*i)) .&. 0xFF
  asmByte $ fromIntegral byte

asmPad :: Word32 -> Asm ()
asmPad n = do
  here <- asmHere
  if here `mod` n == 0 then pure ()
  else asmByte 0 >> asmPad n

asmAscii :: String -> Asm ()
asmAscii str = forM_ str $ \c ->
  asmByte (fromIntegral $ ord c .&. 0x7F)

asmAsciiz :: String -> Asm ()
asmAsciiz str = asmAscii str >> asmByte 0

asmBlock :: [Asm ()] -> Asm (Word32, Word32)
asmBlock text = do
  a <- asmHere
  forM_ text id
  b <- asmHere
  pure (a, b)

------ Printing ------

hexdump :: [Word8] -> String
hexdump bytes =
  let hexBytes = concat $ hexByte <$> bytes
      hexLines = chunksOf 4 <$> chunksOf 32 hexBytes
   in unlines (unwords <$> hexLines)

------ Assembly Monad ------

newtype Asm a = Asm { unAsm :: State AsmSt a }
  deriving(Functor, Applicative, Monad, MonadFix)
data AsmSt = AsmSt
  { asmCur :: Word32
  , asmOut :: [Word8]
  }

runAsm :: Asm a -> [Word8]
runAsm action = adapt $ execState (unAsm action) st0
  where
  adapt AsmSt{..} =
    let shebang = (fromIntegral . ord) <$>
          "#!/usr/bin/env  kiss-vm        \n"
        magic = (fromIntegral . ord) <$>
          "kiss vm\0" ++ "\0\0\0\0\0\0\0\0"
      in shebang ++ magic ++ reverse asmOut
  st0 = AsmSt
    { asmCur = 0
    , asmOut = []
    }

asmInstr :: Word16 -> Asm ()
asmInstr code = do
  asmByte $ fromIntegral (code .&. 0xFF)
  asmByte $ fromIntegral (code `shiftR` 8)

---------------------
------ Helpers ------
---------------------

both :: (a -> b) -> (a, a) -> (b, b)
both f (x, y) = (f x, f y)

swap :: (a, b) -> (b, a)
swap (a, b) = (b, a)

-- | Bitwise nor.
infixl 5 .~|.
(.~|.) :: Bits a => a -> a -> a
a .~|. b = complement (a .|. b)

chunksOf :: Int -> [a] -> [[a]]
chunksOf _ [] = []
chunksOf n xs =
  let (group, rest) = splitAt n xs
   in group : chunksOf n rest

hexByte :: Word8 -> String
hexByte b
  | b < 0x10 = '0' : showHex b ""
  | otherwise = showHex b ""
